name: docs
on:
  push:
    branches:
      - master
      - CI_check
      - CI_check_pip

jobs:
  build-and-publish:
    concurrency: docs-${{ github.ref }} #to stop simultaneous docs builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Julia ${{ matrix.julia-version }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Build HiQGA
      - uses: julia-actions/julia-buildpkg@latest
      - name: Test HiQGA
      - uses: julia-actions/julia-runtest@latest
#       - name: import HiQGA
#         run: |
#           echo "not skipping"
#           julia -E 'import HiQGA'
      # - name: Publish docs
      #   uses: JamesIves/github-pages-deploy-action@v4.4.3
      #   with:
      #     branch: gh-pages
      #     folder: docs/build
