name: docs

on:
  push:
    branches: 
    - CI_check_pip
    
jobs:
  build-and-publish:
    concurrency: docs-${{ github.ref }} #to stop simultaneous docs builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Julia ${{ matrix.julia-version }}
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install Documenter and hack PyPlot to use automanaged Conda
        run: |
          julia -e 'using Pkg; Pkg.add(["Documenter", "Literate"])'
      - uses: julia-actions/julia-buildpkg@latest
      - name: Build docs
        run: |
          cd docs
          julia make.jl
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs/build

