name: docs
on:
  push:
    branches:
      - master
      - CI_check
jobs:
  build-and-publish:
    concurrency: docs-${{ github.ref }} #to stop simultaneous docs builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.2.1
        with:
          # Whether to activate the conda base env (Default: 'true')
          activate-conda: true
          # If conda should be updated before running other commands (Default: 'false')
          update-conda: false
          # Python version which should be installed with conda (default: 'Default')
          python-version: default
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: true   
      - name: Set up Julia ${{ matrix.julia-version }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install Documenter and use automanaged Conda
        run: |
          julia -e 'using Pkg; Pkg.add(["Documenter", "Literate", "PyCall", "Conda"])'; \
          julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.build("PyCall")'; \
          julia -e 'using Conda; Conda.add("matplotlib", channel="conda-forge")'
      - name: Install HiQGA in Julia
        run: |
          julia -e 'using Pkg; Pkg.develop(path=".")'
      - name: Build docs
        run: |
          cd docs
          julia make.jl
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs/build
